### ISSUE TITLE
peer-to-peer code review 

### ISSUE THREAD

**Issue by AbdollahRaafat** [rdnrn/to-do-list#3]
Hi,
Great job.

I think you implemented the project perfectly.

Maybe the simplicity here will make the unique ID for adding to the list better:

https://github.com/rdnrn/to-do-list/blob/88c386f936b7ca5283f506277fb39647c789d32d/src/addRemove.js#L11

if we use a simple counter and add it as an id more simple and elegant.

**Comment by arnrdn** [comment]
Thank you for the suggestion!
